### ISSUE TITLE
TypeError: Unsupported integer size (0) when using SAM to generate 17places_r_masks_320.h5

### ISSUE THREAD

**Issue by Diffcc** [AnyLoc/Revisit-Anything#3]
Hello, I am very interested in your work, but I encountered an issue while trying to run the following command:

`python place_rec_SAM_DINO.py --dataset 17places --method DINO/SAM`

When using the DINO option, everything works fine, and I am able to generate the 17places_q_dino_640.h5 and 17places_r_dino_640.h5 files without issues. However, when switching to the SAM method, I get the following error when trying to generate the HDF5 file:

```
Traceback (most recent call last):
  File "/home/server/hdd-0/meng/Project/Loc/Revisit-Anything/place_rec_SAM_DINO.py", line 138, in <module>
    func_vpr.process_SAM_to_h5(h5FullPathSAM, cfg_sam, ims, SAM, dataDir=dataPath)
  File "/home/server/hdd-0/meng/Project/Loc/Revisit-Anything/func_vpr.py", line 684, in process_SAM_to_h5
    mask_grp.create_dataset("area", data=np.array([m['area']], dtype=np.int32))
  File "/home/server/anaconda3/envs/anyloc/lib/python3.9/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/server/anaconda3/envs/anyloc/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 87, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1669, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1693, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1711, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1465, in h5py.h5t._c_int
TypeError: Unsupported integer size (0)
```

related code：
```
def process_SAM_to_h5(h5FullPath,cfg,ims,models,device="cuda",dataDir="./"):
    rmin = cfg['rmin']
    with h5py.File(h5FullPath, "w") as f:
        for i, _ in enumerate(tqdm(ims)):
            if isinstance(ims[0],str):
                imname = ims[i] 
                im = cv2.imread(f'{dataDir}/{imname}')[rmin:,:,:]
            else:
                imname, im = i, ims[i][rmin:,:,:]
            im_p, masks = process_single_SAM(cfg,im,models,device)
            grp = f.create_group(f"{imname}")
            grp.create_group("masks")
            for j, m in enumerate(masks):
                for k in m.keys():
                    print(f"Key: {k}, Type: {type(m[k])}, Shape: {getattr(m[k], 'shape', None)}")
                    grp["masks"].create_dataset(f"{j}/{k}", data=m[k])
```

the following keys and types are present in the output:
```
Key: segmentation, Type: <class 'numpy.ndarray'>, Shape: (240, 320)
Key: area, Type: <class 'int'>, Shape: None
```

It seems that the error occurs when trying to create a dataset from the m['area'] field, and the data type used is not supported by h5py. I am using h5py version 3.12.1. I am unsure if this is a version-related issue or a bug in the code.

**Comment by Shubodh** [comment]
Hello, thanks for your interest in our work.
It is likely due to h5py version. We will share environment config in next 2 days which should hopefully fix this. 
Thank you for your patience!

**Comment by Diffcc** [comment]
Thank you for your reply. I have lowered it to version 3.0.0 and it can now run normally.

**Comment by Shubodh** [comment]
Yup, if you prefer a higher version, 3.10.0 should also work. 
Thank you
